apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-backend-secrets" .Release.Name) .Values.django.existingSecret }}
  labels:
    app: {{ .Release.Name }}-backend
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.django.secretKey | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}