apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom-scrapper-engine
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Alii0319/Ecommerce-Scraper-Engine.git
    targetRevision: main         # e.g., main ya master
    path: K8S/Umbrella-chart # e.g., K8S/Umbrella-chart
    # Helm charts ke liye niche wale section ko uncomment karen:
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecom-scrapper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m