# Generated by Django 5.0.14 on 2026-07-21 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0002_trackedproduct_last_alerted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'scraped_at'], name='trackers_pr_product_57bf78_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedproduct',
            index=models.Index(fields=['user', 'is_active'], name='trackers_tr_user_id_bd5825_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='positive_price_history_price'),
        ),
        migrations.AddConstraint(
            model_name='trackedproduct',
            constraint=models.UniqueConstraint(fields=('user', 'target_url'), name='unique_user_target_url'),
        ),
        migrations.AddConstraint(
            model_name='trackedproduct',
            constraint=models.CheckConstraint(check=models.Q(('notification_threshold__gte', 0)), name='positive_notification_threshold'),
        ),
    ]
