# Generated by Django 5.0.14 on 2026-07-21 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackers', '0003_pricehistory_trackers_pr_product_57bf78_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackedproduct',
            name='last_scrape_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='trackedproduct',
            name='last_scrape_error_message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trackedproduct',
            name='last_scrape_status',
            field=models.CharField(default='never', max_length=32),
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('alert_type', models.CharField(choices=[('threshold_reached', 'Threshold reached'), ('new_lower_price', 'New lower price'), ('price_drop', 'Price drop')], max_length=32)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trackers.pricehistory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trackers.trackedproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'available_at'], name='alert_delivery_queue_idx'), models.Index(fields=['user', '-created_at'], name='alert_user_created_idx')],
            },
        ),
    ]
