# Generated by Django 5.0.14 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackers", "0004_trackedproduct_consecutive_failures_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricealert",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("published", "Published to Channels"),
                    ("acknowledged", "Acknowledged by browser"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.RenameField(
            model_name="pricealert",
            old_name="delivered_at",
            new_name="published_at",
        ),
        migrations.AddField(
            model_name="pricealert",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
